name: Deploy Website
on:
  workflow_dispatch:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push Docker image
          run: |
            docker build -t vera23/my-nginx-image .
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u vera23 --password-stdin
            docker push vera23/my-nginx-image:latest
            
      # - name: Deploy to server
      #   run: |
      #     ssh user@server 'docker pull username/my-nginx-image:latest && docker stop my-nginx-container && docker rm my-nginx-container && docker run -d -p 80:80 --name my-nginx-container username/my-nginx-image:latest'



